#!/usr/bin/env node
// PreCompact hook: snapshot key context files to docs/context-bundles/ before
// the conversation is compacted. Preserves what Claude would need to resume
// without a full /context-dump — reads static files, not synthesised output.

const fs = require('node:fs');
const path = require('node:path');
const { execSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..', '..');
const BUNDLES_DIR = path.join(ROOT, 'docs', 'context-bundles');

function read(rel) {
  try { return fs.readFileSync(path.join(ROOT, rel), 'utf8').trimEnd(); }
  catch { return '(not found)'; }
}

function exec(cmd) {
  try { return execSync(cmd, { cwd: ROOT, encoding: 'utf8' }).trimEnd(); }
  catch { return '(command failed)'; }
}

// Determine label from stdin (PreCompact passes {"reason":"manual"|"auto"})
let label = 'auto-compact';
try {
  const raw = fs.readFileSync(0, 'utf8'); // fd 0 = stdin, cross-platform
  const payload = JSON.parse(raw);
  label = payload.reason === 'manual' ? 'manual-compact' : 'auto-compact';
} catch { /* stdin unavailable or not JSON — use default label */ }

const now = new Date();
const pad = (n) => String(n).padStart(2, '0');
const stamp =
  `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}` +
  `-${pad(now.getHours())}${pad(now.getMinutes())}`;

const outPath = path.join(BUNDLES_DIR, `${stamp}-${label}.md`);

// Don't overwrite an existing bundle written this same minute
if (fs.existsSync(outPath)) process.exit(0);

fs.mkdirSync(BUNDLES_DIR, { recursive: true });

const phaseLine = (() => {
  const m = read('CLAUDE.md').match(/\*\*Current phase:\*\*\s*(.+)/);
  return m ? m[1].trim() : 'unknown';
})();

const branch = exec('git rev-parse --abbrev-ref HEAD');
const headHash = exec('git log -1 --format="%h"');
const gitLog = exec('git log --oneline -10');
const gitStatus = exec('git status --short');

const checkpoint = read('docs/checkpoints/latest.md');
const claudeMd = read('CLAUDE.md');

// Detect active PRD number from CLAUDE.md phase line
const prdMatch = phaseLine.match(/Phase\s+(\d+)/i);
const prdNum = prdMatch ? prdMatch[1] : '1';
const prd = read(`docs/prds/phase-${prdNum}.md`);

const bundle = `\
# Chronimage context bundle · ${stamp} · ${label}

> Auto-generated by PreCompact hook before context compaction.
> Use \`/context-load ${path.relative(ROOT, outPath).replace(/\\/g, '/')}\` to resume.

## 1. Current phase marker
**Current phase:** ${phaseLine}

## 2. Working directory & branch
- path: \`${ROOT}\`
- branch: \`${branch}\`
- head: \`${headHash}\`

## 3. Recent git history
\`\`\`
${gitLog}
\`\`\`

## 4. Uncommitted changes
\`\`\`
${gitStatus || '(clean)'}
\`\`\`

## 5. Latest checkpoint
\`\`\`markdown
${checkpoint}
\`\`\`

## 6. Active PRD (phase-${prdNum}.md)
\`\`\`markdown
${prd}
\`\`\`

## 7. CLAUDE.md (full)
\`\`\`markdown
${claudeMd}
\`\`\`
`;

fs.writeFileSync(outPath, bundle, 'utf8');

// Surface the path in the compaction summary so Claude sees it after resuming
console.log(
  JSON.stringify({
    additionalContext: `Context snapshot saved before compaction: ${path.relative(ROOT, outPath).replace(/\\/g, '/')} — run /context-load to restore working context in a fresh session.`,
  }),
);

process.exit(0);
