-- Migration: initial
-- Created: 2026-04-19T00:00:00Z
-- Phase: 0 — foundation
--
-- Forward-only. Do not edit this file once merged to develop.
-- Paired Rust struct changes are in src-tauri/src/catalog/models.rs.
-- sqlx wraps each migration in its own transaction; no BEGIN/COMMIT here.
--
-- PRAGMAs are set on each connection by SqliteConnectOptions, not per-migration.

-- Photos: canonical identity is sha256.
CREATE TABLE IF NOT EXISTS photos (
  id               INTEGER PRIMARY KEY,
  sha256           TEXT    NOT NULL UNIQUE,
  filename         TEXT    NOT NULL,
  width            INTEGER NOT NULL,
  height           INTEGER NOT NULL,
  captured_at      TEXT,           -- ISO-8601 UTC
  imported_at      TEXT    NOT NULL,
  is_raw           INTEGER NOT NULL DEFAULT 0 CHECK (is_raw IN (0,1)),
  paired_photo_id  INTEGER REFERENCES photos(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_photos_captured_at ON photos(captured_at);
CREATE INDEX IF NOT EXISTS idx_photos_imported_at ON photos(imported_at);
CREATE INDEX IF NOT EXISTS idx_photos_paired ON photos(paired_photo_id);

-- Sources: one row per connected source (local disk, Google Photos, iPhone, etc.)
CREATE TABLE IF NOT EXISTS sources (
  id            INTEGER PRIMARY KEY,
  name          TEXT    NOT NULL,
  kind          TEXT    NOT NULL,  -- 'local' | 'external' | 'nas' | 'sd' | 'iphone' | 'android' | 'google_photos' | 'icloud' | 'onedrive' | 'dropbox'
  status        TEXT    NOT NULL DEFAULT 'idle', -- 'idle' | 'syncing' | 'ready' | 'paused' | 'synced' | 'error'
  config_json   TEXT    NOT NULL DEFAULT '{}' CHECK (json_valid(config_json)),
  created_at    TEXT    NOT NULL,
  last_scan_at  TEXT
);

-- Source copies: many-to-one against photos (same photo can live in multiple places simultaneously).
CREATE TABLE IF NOT EXISTS source_copies (
  id                 INTEGER PRIMARY KEY,
  photo_id           INTEGER NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
  source_id          INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  external_id        TEXT,                           -- e.g. Google Photos mediaItem id
  path               TEXT,                           -- local filesystem path if applicable
  is_primary         INTEGER NOT NULL DEFAULT 0 CHECK (is_primary IN (0,1)),
  verified_sha256    TEXT,
  last_seen_at       TEXT NOT NULL,
  UNIQUE(source_id, external_id),
  UNIQUE(source_id, path)
);

CREATE INDEX IF NOT EXISTS idx_source_copies_photo ON source_copies(photo_id);
CREATE INDEX IF NOT EXISTS idx_source_copies_source ON source_copies(source_id);

-- Import runs.
CREATE TABLE IF NOT EXISTS imports (
  id               INTEGER PRIMARY KEY,
  source_id        INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  started_at       TEXT    NOT NULL,
  finished_at      TEXT,
  total_files      INTEGER NOT NULL DEFAULT 0,
  imported_count   INTEGER NOT NULL DEFAULT 0,
  error_count      INTEGER NOT NULL DEFAULT 0,
  last_seen_path   TEXT                                 -- for resume
);

CREATE INDEX IF NOT EXISTS idx_imports_source ON imports(source_id);

-- Global settings KV.
CREATE TABLE IF NOT EXISTS settings (
  key    TEXT PRIMARY KEY,
  value  TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Seed: schema version as the only initial setting so app start-up can detect "fresh install".
INSERT OR IGNORE INTO settings(key, value, updated_at)
VALUES ('schema_version', '1', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));
