// Library screen + side panel of smart albums
const { useState: useState_lib, useMemo } = React;

const LibrarySidePanel = ({ albumId, setAlbumId }) => {
  const all = { id: "all", name: "All Photos", count: 851002 };
  return (
    <div className="sidepanel">
      <div className="head">
        <h3>Library</h3>
        <span className="count">851,002</span>
      </div>
      <div className="section-label">
        <span>Smart Albums</span>
        <span className="ai-badge on"><Icon name="ai" size={10}/> AI</span>
      </div>
      <div className="list">
        <button className={`item ${albumId==="all"?"active":""}`} onClick={()=>setAlbumId("all")}>
          <span className="ico"><Icon name="layers" size={15}/></span>
          All Photos
          <span className="n">{all.count.toLocaleString()}</span>
        </button>
        {ALBUMS.filter(a=>a.tag!=="cull").map(a => (
          <button key={a.id} className={`item ${albumId===a.id?"active":""}`} onClick={()=>setAlbumId(a.id)}>
            <span className="ico"><Icon name={a.tag==="faces"||a.tag==="people"?"faces": a.tag==="event"?"star": "tag"} size={14}/></span>
            <span style={{flex:1, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap'}}>{a.name}</span>
            <span className="n">{a.count.toLocaleString()}</span>
          </button>
        ))}
      </div>

      <div className="section-label"><span>Cull queue</span><span className="ai-badge">auto</span></div>
      <div className="list">
        {ALBUMS.filter(a=>a.tag==="cull").map(a => (
          <button key={a.id} className={`item ${albumId===a.id?"active":""}`} onClick={()=>setAlbumId(a.id)}>
            <span className="ico" style={{color:'var(--warn)'}}><Icon name="flag" size={14}/></span>
            <span style={{flex:1}}>{a.name}</span>
            <span className="n">{a.count.toLocaleString()}</span>
          </button>
        ))}
      </div>

      <div className="section-label"><span>People</span><span className="ai-badge on">{PEOPLE.length}</span></div>
      <div className="list" style={{padding: '0 10px 10px'}}>
        <div style={{display:'grid', gridTemplateColumns:'repeat(6,1fr)', gap:6}}>
          {PEOPLE.map(p => (
            <div key={p.name} title={`${p.name} · ${p.count}`} style={{textAlign:'center'}}>
              <div style={{width: 32, height: 32, borderRadius: '50%', overflow:'hidden', background:`oklch(0.5 0.15 ${PHOTOS[p.face].hue})`, border:'1px solid var(--stroke)'}}/>
              <div style={{fontSize: 9.5, color:'var(--fg-mute)', marginTop: 3, fontFamily: 'var(--mono-font)'}}>{p.name}</div>
            </div>
          ))}
        </div>
      </div>

      <div style={{marginTop:'auto', padding: 12, borderTop:'1px solid var(--stroke)'}}>
        <div style={{fontSize: 11, fontFamily:'var(--mono-font)', color:'var(--fg-mute)', marginBottom: 6, display:'flex', justifyContent:'space-between'}}>
          <span>Indexing</span><span>99.6%</span>
        </div>
        <div className="progress"><div style={{width:'99.6%'}}/></div>
        <div style={{fontSize: 10.5, color:'var(--fg-mute)', marginTop: 6, fontFamily:'var(--mono-font)'}}>3,711 photos remaining · faces, scenes, OCR</div>
      </div>
    </div>
  );
};

const LibraryAlbumsView = ({ setAlbumId, setScreen }) => (
  <>
    <div style={{padding: '24px 24px 8px'}}>
      <h1 className="display" style={{fontSize: 72, margin:0}}>Eight hundred fifty-one<br/>thousand moments, <em>sorted.</em></h1>
      <p style={{color:'var(--fg-dim)', maxWidth: 640, fontSize: 14, lineHeight:1.5, marginTop: 16}}>
        Chronimage re-reads your library every night. Smart albums are generated by gemma4 on-device — no photos leave your machine. Tap one to browse, or jump to the cull queue to burn through duplicates.
      </p>
    </div>
    <div className="album-row">
      {ALBUMS.map(a => (
        <div key={a.id} className="album-card" onClick={()=>{ setAlbumId(a.id); }}>
          <div className="cover">
            {a.covers.map((ci, k) => (
              <div key={k} className="ph" style={{ background: `linear-gradient(135deg, oklch(0.55 0.18 ${a.tint + k*20}), oklch(0.22 0.08 ${a.tint + k*20}))` }}/>
            ))}
          </div>
          <div className="meta">
            <div className="t">{a.name}</div>
            <div className="s">
              <span className="pill">{a.count.toLocaleString()} photos</span>
              <span className="pill" style={{color:'var(--fg-dim)'}}>{a.desc}</span>
            </div>
          </div>
        </div>
      ))}
    </div>
  </>
);

const LibraryGridView = ({ album }) => {
  const [selected, setSelected] = useState_lib(new Set([5, 12]));
  const photos = useMemo(() => PHOTOS.slice(0, 36), []);
  const toggle = (i) => {
    const s = new Set(selected);
    s.has(i) ? s.delete(i) : s.add(i);
    setSelected(s);
  };
  return (
    <>
      <div style={{padding: '20px 24px 4px', display:'flex', alignItems:'flex-end', justifyContent:'space-between', gap: 20, flexWrap:'wrap'}}>
        <div>
          <div className="mono" style={{fontSize: 11, color:'var(--fg-mute)', marginBottom: 6}}>SMART ALBUM · AUTO-CURATED</div>
          <h1 className="display" style={{fontSize: 52, margin:0, fontWeight: 400}}>{album.name}</h1>
          <div className="mono" style={{fontSize: 12, color:'var(--fg-dim)', marginTop: 8}}>{album.count.toLocaleString()} photos · {album.desc}</div>
        </div>
        <div style={{display:'flex', gap: 8, alignItems:'center'}}>
          <Chip tone="info">CLIP similarity · 0.82+</Chip>
          <Chip tone="">Face match · 98%</Chip>
          <Chip tone="">Last updated 2h ago</Chip>
        </div>
      </div>
      <div className="facetbar">
        {['All', 'People', 'Places', 'Objects', 'Events', 'Colors', 'Cameras'].map(f => (
          <button key={f} className="btn" style={{border:'1px solid var(--stroke)'}}>{f}</button>
        ))}
      </div>
      <div style={{padding: '14px 24px 0', display:'flex', gap: 8, flexWrap:'wrap'}}>
        <Chip variant="solid">Ari</Chip>
        <Chip>Backyard</Chip>
        <Chip>Golden hour</Chip>
        <Chip>Summer '25</Chip>
        <Chip>Canon R6</Chip>
        <span style={{fontSize: 12, color:'var(--fg-mute)', marginLeft: 6}}>and 14 more refinements</span>
      </div>
      <div className="libgrid">
        {photos.map((p, i) => (
          <div key={p.id} className="cell" onClick={()=>toggle(i)}>
            <Placeholder photo={p} idx={i} selected={selected.has(i)} subtle />
          </div>
        ))}
      </div>
    </>
  );
};

const LibraryScreen = ({ albumId, setAlbumId, setScreen }) => {
  const album = ALBUMS.find(a=>a.id===albumId);
  return (
    <div className="canvas">
      <div className="toolbar">
        <div className="search">
          <Icon name="search" size={14}/>
          <input placeholder="Describe what you're looking for — e.g. 'Ari laughing at the beach'"/>
          <span className="kbd">⌘K</span>
        </div>
        <div className="divider"/>
        <button className="btn"><Icon name="grid" size={14}/> Grid</button>
        <button className="btn"><Icon name="layers" size={14}/> Stacks</button>
        <div style={{flex: 1}}/>
        <button className="btn ghost"><Icon name="tag" size={14}/> Tags</button>
        <button className="btn primary"><Icon name="sparkles" size={14}/> Re-tag with AI</button>
      </div>
      <div className="canvas-scroll">
        {albumId === "all" ? <LibraryAlbumsView setAlbumId={setAlbumId} setScreen={setScreen}/> : <LibraryGridView album={album}/>}
      </div>
    </div>
  );
};

Object.assign(window, { LibrarySidePanel, LibraryScreen });
